### ISSUE TITLE
package does not work for debug builds

### ISSUE THREAD

**Issue by eugenwintersberger** [ess-dmsc/conan-gtest#1]
When creating the package with `-s build_type=Debug` already the package test fails on Linux (Debian 8).

**Comment by eugenwintersberger** [comment]
Ok. I have fixed this but I still need permissions to push the issue branch ;)

**Comment by martukas** [comment]
This is actually still an issue. If I run conan from inside CMake, see [h5cpp/issue_225](https://github.com/ess-dmsc/h5cpp/tree/issue_225), it fails to find GTest.
